language: elixir
elixir:
  - 1.9
otp_release:
  - 22.1.8
env:
  - MIX_ENV=test
cache:
  directories:
    - _build
    - deps
services:
  - postgresql
env:
  global:
    - MIX_ENV=test
before_script:
  - mix do ecto.create, ecto.migrate
script:
  - mix cover
after_success:
  - bash <(curl -s https://codecov.io/bash)